/*
 * FILE : AHDLuaWrap.c
 * 
 * This file was automatically generated by :
 * Simplified Wrapper and Interface Generator (SWIG)
 * Version 1.1 (Patch 5)
 * 
 * Portions Copyright (c) 1995-1998
 * The University of Utah and The Regents of the University of California.
 * Permission is granted to distribute this file in any manner provided
 * this notice remains intact.
 * 
 * Do not make changes to this file--changes will be lost!
 *
 */


#define SWIGCODE
/* Implementation : Lua */

#include <lua.h>

#ifdef __cplusplus
extern "C" {
#endif
extern void SWIG_MakePtr(char *, void *, char *);
extern void SWIG_RegisterMapping(char *, char *, void *(*)(void *));
extern char *SWIG_GetPtr(char *, void **, char *);
#ifdef __cplusplus
}
#endif

#ifdef NATIVE_NETWORKING
#include <errno.h>
#include <signal.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <sys/fcntl.h>
#include <sys/wait.h>
#include <netinet/in.h>
#include <netdb.h>
#include <regex.h>

#ifdef HAVE_LIBPTHREAD
#include <pthread.h>
#endif

#include <Net.h>
#endif

#include <KinoParser.h>
#include <AHDRuntime.h>

static void _wrap_AHDRuntimeNew(void) {

    AHDRuntime * _result;
    int  _arg0;
    char * _arg1;

{
  _arg0 = (int ) lua_getnumber (lua_getparam (1));
}
{
  _arg1 = lua_getstring (lua_getparam (2));
}
    _result = (AHDRuntime *)AHDRuntimeNew(_arg0,_arg1);
{
  if (_result != NULL) lua_pushuserdata (_result);
  else lua_pushnil ();
}
    
}
static void _wrap_AHDRuntimeDelete(void) {

    AHDRuntime * _arg0;

{
  if (!lua_isnil (lua_getparam (1))) _arg0 = lua_getuserdata (lua_getparam (1));
  else _arg0 = NULL;
}
    AHDRuntimeDelete(_arg0);
    
}
static void _wrap_AHDRuntimeAddScriptHandler(void) {

    AHDRuntime * _arg0;
    HandlerProc * _arg1;
    void * _arg2;

{
  if (!lua_isnil (lua_getparam (1))) _arg0 = lua_getuserdata (lua_getparam (1));
  else _arg0 = NULL;
}
{
  if (!lua_isnil (lua_getparam (2))) _arg1 = lua_getuserdata (lua_getparam (2));
  else _arg1 = NULL;
}
{
  if (!lua_isnil (lua_getparam (3))) _arg2 = lua_getuserdata (lua_getparam (3));
  else _arg2 = NULL;
}
    AHDRuntimeAddScriptHandler(_arg0,*_arg1,_arg2);
    
}
static void _wrap_AHDRuntimeDocumentInit(void) {

    AHDRuntime * _arg0;
    Document * _arg1;

{
  if (!lua_isnil (lua_getparam (1))) _arg0 = lua_getuserdata (lua_getparam (1));
  else _arg0 = NULL;
}
{
  if (!lua_isnil (lua_getparam (2))) _arg1 = lua_getuserdata (lua_getparam (2));
  else _arg1 = NULL;
}
    AHDRuntimeDocumentInit(_arg0,_arg1);
    
}
static void _wrap_AHDRuntimeLoad(void) {

    Document * _result;
    AHDRuntime * _arg0;
    char * _arg1;

{
  if (!lua_isnil (lua_getparam (1))) _arg0 = lua_getuserdata (lua_getparam (1));
  else _arg0 = NULL;
}
{
  _arg1 = lua_getstring (lua_getparam (2));
}
    _result = (Document *)AHDRuntimeLoad(_arg0,_arg1);
{
  if (_result != NULL) lua_pushuserdata (_result);
  else lua_pushnil ();
}
    
}
static void _wrap_AHDRuntimeUnload(void) {

    AHDRuntime * _arg0;
    Document * _arg1;

{
  if (!lua_isnil (lua_getparam (1))) _arg0 = lua_getuserdata (lua_getparam (1));
  else _arg0 = NULL;
}
{
  if (!lua_isnil (lua_getparam (2))) _arg1 = lua_getuserdata (lua_getparam (2));
  else _arg1 = NULL;
}
    AHDRuntimeUnload(_arg0,_arg1);
    
}
static void _wrap_AHDRuntimeSave(void) {

    AHDRuntime * _arg0;
    Document * _arg1;

{
  if (!lua_isnil (lua_getparam (1))) _arg0 = lua_getuserdata (lua_getparam (1));
  else _arg0 = NULL;
}
{
  if (!lua_isnil (lua_getparam (2))) _arg1 = lua_getuserdata (lua_getparam (2));
  else _arg1 = NULL;
}
    AHDRuntimeSave(_arg0,_arg1);
    
}
static void _wrap_AHDRuntimeStore(void) {

    AHDRuntime * _arg0;
    Document * _arg1;
    char * _arg2;
    char * _arg3;

{
  if (!lua_isnil (lua_getparam (1))) _arg0 = lua_getuserdata (lua_getparam (1));
  else _arg0 = NULL;
}
{
  if (!lua_isnil (lua_getparam (2))) _arg1 = lua_getuserdata (lua_getparam (2));
  else _arg1 = NULL;
}
{
  _arg2 = lua_getstring (lua_getparam (3));
}
{
  _arg3 = lua_getstring (lua_getparam (4));
}
    AHDRuntimeStore(_arg0,_arg1,_arg2,_arg3);
    
}
static void _wrap_AHDRuntimeCall(void) {

    char * _result;
    AHDRuntime * _arg0;
    Node * _arg1;
    char * _arg2;
    char * _arg3;

{
  if (!lua_isnil (lua_getparam (1))) _arg0 = lua_getuserdata (lua_getparam (1));
  else _arg0 = NULL;
}
{
  if (!lua_isnil (lua_getparam (2))) _arg1 = lua_getuserdata (lua_getparam (2));
  else _arg1 = NULL;
}
{
  _arg2 = lua_getstring (lua_getparam (3));
}
{
  _arg3 = lua_getstring (lua_getparam (4));
}
    _result = (char *)AHDRuntimeCall(_arg0,_arg1,_arg2,_arg3);
{
  lua_pushstring (_result);
}
    
}
static void _wrap_AHDRuntimeBroadcastCall(void) {

    AHDRuntime * _arg0;
    Node * _arg1;
    char * _arg2;
    char * _arg3;

{
  if (!lua_isnil (lua_getparam (1))) _arg0 = lua_getuserdata (lua_getparam (1));
  else _arg0 = NULL;
}
{
  if (!lua_isnil (lua_getparam (2))) _arg1 = lua_getuserdata (lua_getparam (2));
  else _arg1 = NULL;
}
{
  _arg2 = lua_getstring (lua_getparam (3));
}
{
  _arg3 = lua_getstring (lua_getparam (4));
}
    AHDRuntimeBroadcastCall(_arg0,_arg1,_arg2,_arg3);
    
}
static void _wrap_AHDRuntimeGet(void) {

    char * _result;
    AHDRuntime * _arg0;
    Node * _arg1;
    char * _arg2;

{
  if (!lua_isnil (lua_getparam (1))) _arg0 = lua_getuserdata (lua_getparam (1));
  else _arg0 = NULL;
}
{
  if (!lua_isnil (lua_getparam (2))) _arg1 = lua_getuserdata (lua_getparam (2));
  else _arg1 = NULL;
}
{
  _arg2 = lua_getstring (lua_getparam (3));
}
    _result = (char *)AHDRuntimeGet(_arg0,_arg1,_arg2);
{
  lua_pushstring (_result);
}
    
}
static void _wrap_AHDRuntimePut(void) {

    char * _result;
    AHDRuntime * _arg0;
    Node * _arg1;
    char * _arg2;
    char * _arg3;

{
  if (!lua_isnil (lua_getparam (1))) _arg0 = lua_getuserdata (lua_getparam (1));
  else _arg0 = NULL;
}
{
  if (!lua_isnil (lua_getparam (2))) _arg1 = lua_getuserdata (lua_getparam (2));
  else _arg1 = NULL;
}
{
  _arg2 = lua_getstring (lua_getparam (3));
}
{
  _arg3 = lua_getstring (lua_getparam (4));
}
    _result = (char *)AHDRuntimePut(_arg0,_arg1,_arg2,_arg3);
{
  lua_pushstring (_result);
}
    
}
static void _wrap_AHDRuntimeMatch(void) {

    NodeList * _result;
    AHDRuntime * _arg0;
    Element * _arg1;
    Element * _arg2;

{
  if (!lua_isnil (lua_getparam (1))) _arg0 = lua_getuserdata (lua_getparam (1));
  else _arg0 = NULL;
}
{
  if (!lua_isnil (lua_getparam (2))) _arg1 = lua_getuserdata (lua_getparam (2));
  else _arg1 = NULL;
}
{
  if (!lua_isnil (lua_getparam (3))) _arg2 = lua_getuserdata (lua_getparam (3));
  else _arg2 = NULL;
}
    _result = (NodeList *)AHDRuntimeMatch(_arg0,_arg1,_arg2);
{
  if (_result != NULL) lua_pushuserdata (_result);
  else lua_pushnil ();
}
    
}
static void _wrap_AHDRuntimeHere(void) {

    char * _result;
    AHDRuntime * _arg0;

{
  if (!lua_isnil (lua_getparam (1))) _arg0 = lua_getuserdata (lua_getparam (1));
  else _arg0 = NULL;
}
    _result = (char *)AHDRuntimeHere(_arg0);
{
  lua_pushstring (_result);
}
    
}
static void _wrap_AHDRuntimeGetLoadedDocuments(void) {

    NodeList * _result;
    AHDRuntime * _arg0;

{
  if (!lua_isnil (lua_getparam (1))) _arg0 = lua_getuserdata (lua_getparam (1));
  else _arg0 = NULL;
}
    _result = (NodeList *)AHDRuntimeGetLoadedDocuments(_arg0);
{
  if (_result != NULL) lua_pushuserdata (_result);
  else lua_pushnil ();
}
    
}
void kinoahdlua_init (void) {
	 lua_register ("AHDRuntimeNew",_wrap_AHDRuntimeNew);
	 lua_register ("AHDRuntimeDelete",_wrap_AHDRuntimeDelete);
	 lua_register ("AHDRuntimeAddScriptHandler",_wrap_AHDRuntimeAddScriptHandler);
	 lua_register ("AHDRuntimeDocumentInit",_wrap_AHDRuntimeDocumentInit);
	 lua_register ("AHDRuntimeLoad",_wrap_AHDRuntimeLoad);
	 lua_register ("AHDRuntimeUnload",_wrap_AHDRuntimeUnload);
	 lua_register ("AHDRuntimeSave",_wrap_AHDRuntimeSave);
	 lua_register ("AHDRuntimeStore",_wrap_AHDRuntimeStore);
	 lua_register ("AHDRuntimeCall",_wrap_AHDRuntimeCall);
	 lua_register ("AHDRuntimeBroadcastCall",_wrap_AHDRuntimeBroadcastCall);
	 lua_register ("AHDRuntimeGet",_wrap_AHDRuntimeGet);
	 lua_register ("AHDRuntimePut",_wrap_AHDRuntimePut);
	 lua_register ("AHDRuntimeMatch",_wrap_AHDRuntimeMatch);
	 lua_register ("AHDRuntimeHere",_wrap_AHDRuntimeHere);
	 lua_register ("AHDRuntimeGetLoadedDocuments",_wrap_AHDRuntimeGetLoadedDocuments);
/*
 * These are the pointer type-equivalency mappings. 
 * (Used by the SWIG pointer type-checker).
 */
	 SWIG_RegisterMapping("_signed_long","_long",0);
	 SWIG_RegisterMapping("_long","_unsigned_long",0);
	 SWIG_RegisterMapping("_long","_signed_long",0);
	 SWIG_RegisterMapping("_unsigned_long","_long",0);
	 SWIG_RegisterMapping("_signed_int","_int",0);
	 SWIG_RegisterMapping("_unsigned_short","_short",0);
	 SWIG_RegisterMapping("_signed_short","_short",0);
	 SWIG_RegisterMapping("_unsigned_int","_int",0);
	 SWIG_RegisterMapping("_short","_unsigned_short",0);
	 SWIG_RegisterMapping("_short","_signed_short",0);
	 SWIG_RegisterMapping("_int","_unsigned_int",0);
	 SWIG_RegisterMapping("_int","_signed_int",0);
}
