/*
 * FILE : AHDTclWrap.c
 * 
 * This file was automatically generated by :
 * Simplified Wrapper and Interface Generator (SWIG)
 * Version 1.1 (Patch 5)
 * 
 * Portions Copyright (c) 1995-1998
 * The University of Utah and The Regents of the University of California.
 * Permission is granted to distribute this file in any manner provided
 * this notice remains intact.
 * 
 * Do not make changes to this file--changes will be lost!
 *
 */


#define SWIGCODE
/* Implementation : TCL 7.x */

#define INCLUDE_TCL    <tcl.h>
#define INCLUDE_TK     <tk.h>
#include INCLUDE_TCL
#include <string.h>
#include <stdlib.h>
#define SWIGTCL
/*
 * $Header: /b2/dmb/SWIG/SWIG1.0b3/swig_lib/tcl/RCS/swigtcl.cfg,v 1.1 1996/05/22 19:47:45 beazley Exp $
 * 
 * swigtcl.cfg
 *
 * This file is modified from a platform independent file provided
 * by Sun.   With any luck this will allow SWIG generated wrapper
 * files to work on Unix, Windows, and Macintosh.
 *
 * Revision History
 * $Log: swigtcl.cfg,v $
 * Revision 1.1  1996/05/22 19:47:45  beazley
 * Initial revision
 *
 *
 * -- Dave Beazley, May 2, 1996.
 *
 *	This file is an example of a Tcl dynamically loadable extension.
 *
 * Copyright (c) 1996 by Sun Microsystems, Inc.
 *
 * See the file "license.terms" for information on usage and redistribution
 * of this file, and for a DISCLAIMER OF ALL WARRANTIES.
 *
 */

#if defined(__WIN32__)
#   define WIN32_LEAN_AND_MEAN
#   include <windows.h>
#   undef WIN32_LEAN_AND_MEAN

/*
 * VC++ has an alternate entry point called DllMain, so we need to rename
 * our entry point.
 */

#   if defined(_MSC_VER)
#	define SWIGEXPORT(a,b) __declspec(dllexport) a b
#	define DllEntryPoint DllMain
#   else
#	if defined(__BORLANDC__)
#	    define SWIGEXPORT(a,b) a _export b
#	else
#	    define SWIGEXPORT(a,b) a b
#	endif
#   endif
#else
#   define SWIGEXPORT(a,b) a b
#endif

/*
 *----------------------------------------------------------------------
 *
 * DllEntryPoint --
 *
 *	This wrapper function is used by Windows to invoke the
 *	initialization code for the DLL.  If we are compiling
 *	with Visual C++, this routine will be renamed to DllMain.
 *	routine.
 *
 * Results:
 *	Returns TRUE;
 *
 * Side effects:
 *	None.
 *
 *----------------------------------------------------------------------
 */

#ifdef __WIN32__
BOOL APIENTRY
DllEntryPoint(HINSTANCE hInst, DWORD reason, LPVOID reserved)
{
    return TRUE;
}
#endif

#ifdef __cplusplus
extern "C" {
#endif
extern void SWIG_MakePtr(char *, void *, char *);
extern void SWIG_RegisterMapping(char *, char *, void *(*)(void *));
extern char *SWIG_GetPtr(char *, void **, char *);
#ifdef __cplusplus
}
#endif
#define SWIG_init    Kinoahd_Init
#define SWIG_name    "kinoahd"
#define SWIG_prefix  ""
#define SWIG_namespace ""

#ifdef __cplusplus
extern "C" {
#endif
#ifdef MAC_TCL
#pragma export on
#endif
SWIGEXPORT(int,Kinoahd_Init)(Tcl_Interp *);
#ifdef MAC_TCL
#pragma export off
#endif
#ifdef __cplusplus
}
#endif

#ifdef NATIVE_NETWORKING
#include <errno.h>
#include <signal.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <sys/fcntl.h>
#include <sys/wait.h>
#include <netinet/in.h>
#include <netdb.h>
#include <regex.h>

#ifdef HAVE_LIBPTHREAD
#include <pthread.h>
#endif

#include <Net.h>
#endif

#include <KinoParser.h>
#include <AHDRuntime.h>

static int _wrap_AHDRuntimeNew(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    AHDRuntime * _result;
    int  _arg0;
    char * _arg1;

    clientData = clientData; argv = argv;
    if ((argc < 3) || (argc > 3)) {
        Tcl_SetResult(interp, "Wrong # args. AHDRuntimeNew { int  } { char * } ",TCL_STATIC);
        return TCL_ERROR;
    }
    _arg0 = (int ) atol(argv[1]);
    _arg1 = argv[2];
    _result = (AHDRuntime *)AHDRuntimeNew(_arg0,_arg1);
    SWIG_MakePtr(interp->result, (void *) _result,"_AHDRuntime_p");
    return TCL_OK;
}
static int _wrap_AHDRuntimeDelete(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    AHDRuntime * _arg0;

    clientData = clientData; argv = argv;
    if ((argc < 2) || (argc > 2)) {
        Tcl_SetResult(interp, "Wrong # args. AHDRuntimeDelete { AHDRuntime * } ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_AHDRuntime_p")) {
    }
    AHDRuntimeDelete(_arg0);
    return TCL_OK;
}
static int _wrap_AHDRuntimeAddScriptHandler(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    AHDRuntime * _arg0;
    HandlerProc * _arg1;
    void * _arg2;

    clientData = clientData; argv = argv;
    if ((argc < 4) || (argc > 4)) {
        Tcl_SetResult(interp, "Wrong # args. AHDRuntimeAddScriptHandler { AHDRuntime * } { HandlerProc * } { void * } ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_AHDRuntime_p")) {
    }
    if (SWIG_GetPtr(argv[2],(void **) &_arg1,"_HandlerProc_p")) {
    }
    if (SWIG_GetPtr(argv[3],(void **) &_arg2,(char *) 0)) {
    }
    AHDRuntimeAddScriptHandler(_arg0,*_arg1,_arg2);
    return TCL_OK;
}
static int _wrap_AHDRuntimeDocumentInit(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    AHDRuntime * _arg0;
    Document * _arg1;

    clientData = clientData; argv = argv;
    if ((argc < 3) || (argc > 3)) {
        Tcl_SetResult(interp, "Wrong # args. AHDRuntimeDocumentInit { AHDRuntime * } { Document * } ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_AHDRuntime_p")) {
    }
    if (SWIG_GetPtr(argv[2],(void **) &_arg1,"_Document_p")) {
    }
    AHDRuntimeDocumentInit(_arg0,_arg1);
    return TCL_OK;
}
static int _wrap_AHDRuntimeLoad(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    Document * _result;
    AHDRuntime * _arg0;
    char * _arg1;

    clientData = clientData; argv = argv;
    if ((argc < 3) || (argc > 3)) {
        Tcl_SetResult(interp, "Wrong # args. AHDRuntimeLoad { AHDRuntime * } { char * } ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_AHDRuntime_p")) {
    }
    _arg1 = argv[2];
    _result = (Document *)AHDRuntimeLoad(_arg0,_arg1);
    SWIG_MakePtr(interp->result, (void *) _result,"_Document_p");
    return TCL_OK;
}
static int _wrap_AHDRuntimeUnload(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    AHDRuntime * _arg0;
    Document * _arg1;

    clientData = clientData; argv = argv;
    if ((argc < 3) || (argc > 3)) {
        Tcl_SetResult(interp, "Wrong # args. AHDRuntimeUnload { AHDRuntime * } { Document * } ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_AHDRuntime_p")) {
    }
    if (SWIG_GetPtr(argv[2],(void **) &_arg1,"_Document_p")) {
    }
    AHDRuntimeUnload(_arg0,_arg1);
    return TCL_OK;
}
static int _wrap_AHDRuntimeSave(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    AHDRuntime * _arg0;
    Document * _arg1;

    clientData = clientData; argv = argv;
    if ((argc < 3) || (argc > 3)) {
        Tcl_SetResult(interp, "Wrong # args. AHDRuntimeSave { AHDRuntime * } { Document * } ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_AHDRuntime_p")) {
    }
    if (SWIG_GetPtr(argv[2],(void **) &_arg1,"_Document_p")) {
    }
    AHDRuntimeSave(_arg0,_arg1);
    return TCL_OK;
}
static int _wrap_AHDRuntimeStore(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    AHDRuntime * _arg0;
    Document * _arg1;
    char * _arg2;
    char * _arg3;

    clientData = clientData; argv = argv;
    if ((argc < 5) || (argc > 5)) {
        Tcl_SetResult(interp, "Wrong # args. AHDRuntimeStore { AHDRuntime * } { Document * } { char * } { char * } ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_AHDRuntime_p")) {
    }
    if (SWIG_GetPtr(argv[2],(void **) &_arg1,"_Document_p")) {
    }
    _arg2 = argv[3];
    _arg3 = argv[4];
    AHDRuntimeStore(_arg0,_arg1,_arg2,_arg3);
    return TCL_OK;
}
static int _wrap_AHDRuntimeCall(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    char * _result;
    AHDRuntime * _arg0;
    Node * _arg1;
    char * _arg2;
    char * _arg3;

    clientData = clientData; argv = argv;
    if ((argc < 5) || (argc > 5)) {
        Tcl_SetResult(interp, "Wrong # args. AHDRuntimeCall { AHDRuntime * } { Node * } { char * } { char * } ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_AHDRuntime_p")) {
    }
    if (SWIG_GetPtr(argv[2],(void **) &_arg1,"_Node_p")) {
    }
    _arg2 = argv[3];
    _arg3 = argv[4];
    _result = (char *)AHDRuntimeCall(_arg0,_arg1,_arg2,_arg3);
    Tcl_SetResult(interp, (char *) _result, TCL_VOLATILE);
    return TCL_OK;
}
static int _wrap_AHDRuntimeBroadcastCall(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    AHDRuntime * _arg0;
    Node * _arg1;
    char * _arg2;
    char * _arg3;

    clientData = clientData; argv = argv;
    if ((argc < 5) || (argc > 5)) {
        Tcl_SetResult(interp, "Wrong # args. AHDRuntimeBroadcastCall { AHDRuntime * } { Node * } { char * } { char * } ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_AHDRuntime_p")) {
    }
    if (SWIG_GetPtr(argv[2],(void **) &_arg1,"_Node_p")) {
    }
    _arg2 = argv[3];
    _arg3 = argv[4];
    AHDRuntimeBroadcastCall(_arg0,_arg1,_arg2,_arg3);
    return TCL_OK;
}
static int _wrap_AHDRuntimeGet(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    char * _result;
    AHDRuntime * _arg0;
    Node * _arg1;
    char * _arg2;

    clientData = clientData; argv = argv;
    if ((argc < 4) || (argc > 4)) {
        Tcl_SetResult(interp, "Wrong # args. AHDRuntimeGet { AHDRuntime * } { Node * } { char * } ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_AHDRuntime_p")) {
    }
    if (SWIG_GetPtr(argv[2],(void **) &_arg1,"_Node_p")) {
    }
    _arg2 = argv[3];
    _result = (char *)AHDRuntimeGet(_arg0,_arg1,_arg2);
    Tcl_SetResult(interp, (char *) _result, TCL_VOLATILE);
    return TCL_OK;
}
static int _wrap_AHDRuntimePut(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    char * _result;
    AHDRuntime * _arg0;
    Node * _arg1;
    char * _arg2;
    char * _arg3;

    clientData = clientData; argv = argv;
    if ((argc < 5) || (argc > 5)) {
        Tcl_SetResult(interp, "Wrong # args. AHDRuntimePut { AHDRuntime * } { Node * } { char * } { char * } ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_AHDRuntime_p")) {
    }
    if (SWIG_GetPtr(argv[2],(void **) &_arg1,"_Node_p")) {
    }
    _arg2 = argv[3];
    _arg3 = argv[4];
    _result = (char *)AHDRuntimePut(_arg0,_arg1,_arg2,_arg3);
    Tcl_SetResult(interp, (char *) _result, TCL_VOLATILE);
    return TCL_OK;
}
static int _wrap_AHDRuntimeMatch(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    NodeList * _result;
    AHDRuntime * _arg0;
    Element * _arg1;
    Element * _arg2;

    clientData = clientData; argv = argv;
    if ((argc < 4) || (argc > 4)) {
        Tcl_SetResult(interp, "Wrong # args. AHDRuntimeMatch { AHDRuntime * } { Element * } { Element * } ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_AHDRuntime_p")) {
    }
    if (SWIG_GetPtr(argv[2],(void **) &_arg1,"_Element_p")) {
    }
    if (SWIG_GetPtr(argv[3],(void **) &_arg2,"_Element_p")) {
    }
    _result = (NodeList *)AHDRuntimeMatch(_arg0,_arg1,_arg2);
    SWIG_MakePtr(interp->result, (void *) _result,"_NodeList_p");
    return TCL_OK;
}
static int _wrap_AHDRuntimeHere(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    char * _result;
    AHDRuntime * _arg0;

    clientData = clientData; argv = argv;
    if ((argc < 2) || (argc > 2)) {
        Tcl_SetResult(interp, "Wrong # args. AHDRuntimeHere { AHDRuntime * } ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_AHDRuntime_p")) {
    }
    _result = (char *)AHDRuntimeHere(_arg0);
    Tcl_SetResult(interp, (char *) _result, TCL_VOLATILE);
    return TCL_OK;
}
static int _wrap_AHDRuntimeGetLoadedDocuments(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    NodeList * _result;
    AHDRuntime * _arg0;

    clientData = clientData; argv = argv;
    if ((argc < 2) || (argc > 2)) {
        Tcl_SetResult(interp, "Wrong # args. AHDRuntimeGetLoadedDocuments { AHDRuntime * } ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_AHDRuntime_p")) {
    }
    _result = (NodeList *)AHDRuntimeGetLoadedDocuments(_arg0);
    SWIG_MakePtr(interp->result, (void *) _result,"_NodeList_p");
    return TCL_OK;
}
SWIGEXPORT(int,Kinoahd_Init)(Tcl_Interp *interp) {
	 if (interp == 0) 
		 return TCL_ERROR;
	 Tcl_CreateCommand(interp, SWIG_prefix "AHDRuntimeNew", _wrap_AHDRuntimeNew, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "AHDRuntimeDelete", _wrap_AHDRuntimeDelete, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "AHDRuntimeAddScriptHandler", _wrap_AHDRuntimeAddScriptHandler, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "AHDRuntimeDocumentInit", _wrap_AHDRuntimeDocumentInit, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "AHDRuntimeLoad", _wrap_AHDRuntimeLoad, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "AHDRuntimeUnload", _wrap_AHDRuntimeUnload, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "AHDRuntimeSave", _wrap_AHDRuntimeSave, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "AHDRuntimeStore", _wrap_AHDRuntimeStore, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "AHDRuntimeCall", _wrap_AHDRuntimeCall, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "AHDRuntimeBroadcastCall", _wrap_AHDRuntimeBroadcastCall, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "AHDRuntimeGet", _wrap_AHDRuntimeGet, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "AHDRuntimePut", _wrap_AHDRuntimePut, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "AHDRuntimeMatch", _wrap_AHDRuntimeMatch, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "AHDRuntimeHere", _wrap_AHDRuntimeHere, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "AHDRuntimeGetLoadedDocuments", _wrap_AHDRuntimeGetLoadedDocuments, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
/*
 * These are the pointer type-equivalency mappings. 
 * (Used by the SWIG pointer type-checker).
 */
	 SWIG_RegisterMapping("_signed_long","_long",0);
	 SWIG_RegisterMapping("_long","_unsigned_long",0);
	 SWIG_RegisterMapping("_long","_signed_long",0);
	 SWIG_RegisterMapping("_unsigned_long","_long",0);
	 SWIG_RegisterMapping("_signed_int","_int",0);
	 SWIG_RegisterMapping("_unsigned_short","_short",0);
	 SWIG_RegisterMapping("_signed_short","_short",0);
	 SWIG_RegisterMapping("_unsigned_int","_int",0);
	 SWIG_RegisterMapping("_short","_unsigned_short",0);
	 SWIG_RegisterMapping("_short","_signed_short",0);
	 SWIG_RegisterMapping("_int","_unsigned_int",0);
	 SWIG_RegisterMapping("_int","_signed_int",0);
	 return TCL_OK;
}
