/*
 * FILE : ParserTclWrap.c
 * 
 * This file was automatically generated by :
 * Simplified Wrapper and Interface Generator (SWIG)
 * Version 1.1 (Patch 5)
 * 
 * Portions Copyright (c) 1995-1998
 * The University of Utah and The Regents of the University of California.
 * Permission is granted to distribute this file in any manner provided
 * this notice remains intact.
 * 
 * Do not make changes to this file--changes will be lost!
 *
 */


#define SWIGCODE
/* Implementation : TCL 7.x */

#define INCLUDE_TCL    <tcl.h>
#define INCLUDE_TK     <tk.h>
#include INCLUDE_TCL
#include <string.h>
#include <stdlib.h>
#define SWIGTCL
/*
 * $Header: /b2/dmb/SWIG/SWIG1.0b3/swig_lib/tcl/RCS/swigtcl.cfg,v 1.1 1996/05/22 19:47:45 beazley Exp $
 * 
 * swigtcl.cfg
 *
 * This file is modified from a platform independent file provided
 * by Sun.   With any luck this will allow SWIG generated wrapper
 * files to work on Unix, Windows, and Macintosh.
 *
 * Revision History
 * $Log: swigtcl.cfg,v $
 * Revision 1.1  1996/05/22 19:47:45  beazley
 * Initial revision
 *
 *
 * -- Dave Beazley, May 2, 1996.
 *
 *	This file is an example of a Tcl dynamically loadable extension.
 *
 * Copyright (c) 1996 by Sun Microsystems, Inc.
 *
 * See the file "license.terms" for information on usage and redistribution
 * of this file, and for a DISCLAIMER OF ALL WARRANTIES.
 *
 */

#if defined(__WIN32__)
#   define WIN32_LEAN_AND_MEAN
#   include <windows.h>
#   undef WIN32_LEAN_AND_MEAN

/*
 * VC++ has an alternate entry point called DllMain, so we need to rename
 * our entry point.
 */

#   if defined(_MSC_VER)
#	define SWIGEXPORT(a,b) __declspec(dllexport) a b
#	define DllEntryPoint DllMain
#   else
#	if defined(__BORLANDC__)
#	    define SWIGEXPORT(a,b) a _export b
#	else
#	    define SWIGEXPORT(a,b) a b
#	endif
#   endif
#else
#   define SWIGEXPORT(a,b) a b
#endif

/*
 *----------------------------------------------------------------------
 *
 * DllEntryPoint --
 *
 *	This wrapper function is used by Windows to invoke the
 *	initialization code for the DLL.  If we are compiling
 *	with Visual C++, this routine will be renamed to DllMain.
 *	routine.
 *
 * Results:
 *	Returns TRUE;
 *
 * Side effects:
 *	None.
 *
 *----------------------------------------------------------------------
 */

#ifdef __WIN32__
BOOL APIENTRY
DllEntryPoint(HINSTANCE hInst, DWORD reason, LPVOID reserved)
{
    return TRUE;
}
#endif

/*****************************************************************************
 * $Header:$
 *
 * swigptr.swg
 *
 * This file contains supporting code for the SWIG run-time type checking
 * mechanism.  The following functions are available :
 *
 * SWIG_RegisterMapping(char *origtype, char *newtype, void *(*cast)(void *));
 *
 *      Registers a new type-mapping with the type-checker.  origtype is the
 *      original datatype and newtype is an equivalent type.  cast is optional
 *      pointer to a function to cast pointer values between types (this
 *      is typically used to cast pointers from derived classes to base classes in C++)
 *      
 * SWIG_MakePtr(char *buffer, void *ptr, char *typestring);
 *     
 *      Makes a pointer string from a pointer and typestring.  The result is returned
 *      in buffer which is assumed to hold enough space for the result.
 *
 * char * SWIG_GetPtr(char *buffer, void **ptr, char *type)
 *
 *      Gets a pointer value from a string.  If there is a type-mismatch, returns
 *      a character string to the received type.  On success, returns NULL.
 *
 *
 * You can remap these functions by making a file called "swigptr.swg" in
 * your the same directory as the interface file you are wrapping.
 *
 * These functions are normally declared static, but this file can be
 * can be used in a multi-module environment by redefining the symbol
 * SWIGSTATIC.
 *****************************************************************************/

#include <stdlib.h>

#ifdef SWIG_GLOBAL
#ifdef __cplusplus
#define SWIGSTATIC extern "C"
#else
#define SWIGSTATIC
#endif
#endif

#ifndef SWIGSTATIC
#define SWIGSTATIC static
#endif


/* SWIG pointer structure */

typedef struct SwigPtrType {
  char               *name;               /* Datatype name                  */
  int                 len;                /* Length (used for optimization) */
  void               *(*cast)(void *);    /* Pointer casting function       */
  struct SwigPtrType *next;               /* Linked list pointer            */
} SwigPtrType;

/* Pointer cache structure */

typedef struct {
  int                 stat;               /* Status (valid) bit             */
  SwigPtrType        *tp;                 /* Pointer to type structure      */
  char                name[256];          /* Given datatype name            */
  char                mapped[256];        /* Equivalent name                */
} SwigCacheType;

/* Some variables  */

static int SwigPtrMax  = 64;           /* Max entries that can be currently held */
                                       /* This value may be adjusted dynamically */
static int SwigPtrN    = 0;            /* Current number of entries              */
static int SwigPtrSort = 0;            /* Status flag indicating sort            */
static int SwigStart[256];             /* Starting positions of types            */

/* Pointer table */
static SwigPtrType *SwigPtrTable = 0;  /* Table containing pointer equivalences  */

/* Cached values */

#define SWIG_CACHESIZE  8
#define SWIG_CACHEMASK  0x7
static SwigCacheType SwigCache[SWIG_CACHESIZE];  
static int SwigCacheIndex = 0;
static int SwigLastCache = 0;

/* Sort comparison function */
static int swigsort(const void *data1, const void *data2) {
	SwigPtrType *d1 = (SwigPtrType *) data1;
	SwigPtrType *d2 = (SwigPtrType *) data2;
	return strcmp(d1->name,d2->name);
}

/* Binary Search function */
static int swigcmp(const void *key, const void *data) {
  char *k = (char *) key;
  SwigPtrType *d = (SwigPtrType *) data;
  return strncmp(k,d->name,d->len);
}

/* Register a new datatype with the type-checker */

SWIGSTATIC 
void SWIG_RegisterMapping(char *origtype, char *newtype, void *(*cast)(void *)) {

  int i;
  SwigPtrType *t = 0,*t1;

  /* Allocate the pointer table if necessary */

  if (!SwigPtrTable) {     
    SwigPtrTable = (SwigPtrType *) malloc(SwigPtrMax*sizeof(SwigPtrType));
    SwigPtrN = 0;
  }
  /* Grow the table */
  if (SwigPtrN >= SwigPtrMax) {
    SwigPtrMax = 2*SwigPtrMax;
    SwigPtrTable = (SwigPtrType *) realloc((char *) SwigPtrTable,SwigPtrMax*sizeof(SwigPtrType));
  }
  for (i = 0; i < SwigPtrN; i++)
    if (strcmp(SwigPtrTable[i].name,origtype) == 0) {
      t = &SwigPtrTable[i];
      break;
    }
  if (!t) {
    t = &SwigPtrTable[SwigPtrN];
    t->name = origtype;
    t->len = strlen(t->name);
    t->cast = 0;
    t->next = 0;
    SwigPtrN++;
  }

  /* Check for existing entry */

  while (t->next) {
    if ((strcmp(t->name,newtype) == 0)) {
      if (cast) t->cast = cast;
      return;
    }
    t = t->next;
  }
  
  /* Now place entry (in sorted order) */

  t1 = (SwigPtrType *) malloc(sizeof(SwigPtrType));
  t1->name = newtype;
  t1->len = strlen(t1->name);
  t1->cast = cast;
  t1->next = 0;            
  t->next = t1;           
  SwigPtrSort = 0;
}

/* Make a pointer value string */

SWIGSTATIC 
void SWIG_MakePtr(char *_c, const void *_ptr, char *type) {
  static char _hex[16] =
  {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
   'a', 'b', 'c', 'd', 'e', 'f'};
  unsigned long _p, _s;
  char _result[20], *_r;    /* Note : a 64-bit hex number = 16 digits */
  _r = _result;
  _p = (unsigned long) _ptr;
  if (_p > 0) {
    while (_p > 0) {
      _s = _p & 0xf;
      *(_r++) = _hex[_s];
      _p = _p >> 4;
    }
    *_r = '_';
    while (_r >= _result)
      *(_c++) = *(_r--);
  } else {
    strcpy (_c, "NULL");
  }
  if (_ptr)
    strcpy (_c, type);
}

/* Define for backwards compatibility */

#define _swig_make_hex   SWIG_MakePtr 

/* Function for getting a pointer value */

SWIGSTATIC 
char *SWIG_GetPtr(char *_c, void **ptr, char *_t)
{
  unsigned long _p;
  char temp_type[256];
  char *name;
  int  i, len;
  SwigPtrType *sp,*tp;
  SwigCacheType *cache;
  int  start, end;
  _p = 0;

  /* Pointer values must start with leading underscore */
  if (*_c == '_') {
      _c++;
      /* Extract hex value from pointer */
      while (*_c) {
	  if ((*_c >= '0') && (*_c <= '9'))
	    _p = (_p << 4) + (*_c - '0');
	  else if ((*_c >= 'a') && (*_c <= 'f'))
	    _p = (_p << 4) + ((*_c - 'a') + 10);
	  else
	    break;
	  _c++;
      }

      if (_t) {
	if (strcmp(_t,_c)) { 
	  if (!SwigPtrSort) {
	    qsort((void *) SwigPtrTable, SwigPtrN, sizeof(SwigPtrType), swigsort); 
	    for (i = 0; i < 256; i++) {
	      SwigStart[i] = SwigPtrN;
	    }
	    for (i = SwigPtrN-1; i >= 0; i--) {
	      SwigStart[(int) (SwigPtrTable[i].name[1])] = i;
	    }
	    for (i = 255; i >= 1; i--) {
	      if (SwigStart[i-1] > SwigStart[i])
		SwigStart[i-1] = SwigStart[i];
	    }
	    SwigPtrSort = 1;
	    for (i = 0; i < SWIG_CACHESIZE; i++)  
	      SwigCache[i].stat = 0;
	  }
	  
	  /* First check cache for matches.  Uses last cache value as starting point */
	  cache = &SwigCache[SwigLastCache];
	  for (i = 0; i < SWIG_CACHESIZE; i++) {
	    if (cache->stat) {
	      if (strcmp(_t,cache->name) == 0) {
		if (strcmp(_c,cache->mapped) == 0) {
		  cache->stat++;
		  *ptr = (void *) _p;
		  if (cache->tp->cast) *ptr = (*(cache->tp->cast))(*ptr);
		  return (char *) 0;
		}
	      }
	    }
	    SwigLastCache = (SwigLastCache+1) & SWIG_CACHEMASK;
	    if (!SwigLastCache) cache = SwigCache;
	    else cache++;
	  }
	  /* We have a type mismatch.  Will have to look through our type
	     mapping table to figure out whether or not we can accept this datatype */

	  start = SwigStart[(int) _t[1]];
	  end = SwigStart[(int) _t[1]+1];
	  sp = &SwigPtrTable[start];
	  while (start < end) {
	    if (swigcmp(_t,sp) == 0) break;
	    sp++;
	    start++;
	  }
	  if (start >= end) sp = 0;
	  /* Try to find a match for this */
	  if (sp) {
	    while (swigcmp(_t,sp) == 0) {
	      name = sp->name;
	      len = sp->len;
	      tp = sp->next;
	      /* Try to find entry for our given datatype */
	      while(tp) {
		if (tp->len >= 255) {
		  return _c;
		}
		strcpy(temp_type,tp->name);
		strncat(temp_type,_t+len,255-tp->len);
		if (strcmp(_c,temp_type) == 0) {
		  
		  strcpy(SwigCache[SwigCacheIndex].mapped,_c);
		  strcpy(SwigCache[SwigCacheIndex].name,_t);
		  SwigCache[SwigCacheIndex].stat = 1;
		  SwigCache[SwigCacheIndex].tp = tp;
		  SwigCacheIndex = SwigCacheIndex & SWIG_CACHEMASK;
		  
		  /* Get pointer value */
		  *ptr = (void *) _p;
		  if (tp->cast) *ptr = (*(tp->cast))(*ptr);
		  return (char *) 0;
		}
		tp = tp->next;
	      }
	      sp++;
	      /* Hmmm. Didn't find it this time */
	    }
	  }
	  /* Didn't find any sort of match for this data.  
	     Get the pointer value and return the received type */
	  *ptr = (void *) _p;
	  return _c;
	} else {
	  /* Found a match on the first try.  Return pointer value */
	  *ptr = (void *) _p;
	  return (char *) 0;
	}
      } else {
	/* No type specified.  Good luck */
	*ptr = (void *) _p;
	return (char *) 0;
      }
  } else {
    if (strcmp (_c, "NULL") == 0) {
	*ptr = (void *) 0;
	return (char *) 0;
    }
    *ptr = (void *) 0;	
    return _c;
  }
}

/* Compatibility mode */

#define _swig_get_hex  SWIG_GetPtr

#define SWIG_init    Kinoparser_Init
#define SWIG_name    "kinoparser"
#define SWIG_prefix  ""
#define SWIG_namespace ""

#ifdef __cplusplus
extern "C" {
#endif
#ifdef MAC_TCL
#pragma export on
#endif
SWIGEXPORT(int,Kinoparser_Init)(Tcl_Interp *);
#ifdef MAC_TCL
#pragma export off
#endif
#ifdef __cplusplus
}
#endif

#ifdef NATIVE_NETWORKING
#include <errno.h>
#include <signal.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <sys/fcntl.h>
#include <sys/wait.h>
#include <netinet/in.h>
#include <netdb.h>
#include <regex.h>

#ifdef HAVE_LIBPTHREAD
#include <pthread.h>
#endif

#include <Net.h>
#endif

#include <KinoParser.h>
#include <AHDRuntime.h>

static int _wrap_NodeNew(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    Node * _result;

    clientData = clientData; argv = argv;
    if ((argc < 1) || (argc > 1)) {
        Tcl_SetResult(interp, "Wrong # args. NodeNew ",TCL_STATIC);
        return TCL_ERROR;
    }
    _result = (Node *)NodeNew();
    SWIG_MakePtr(interp->result, (void *) _result,"_Node_p");
    return TCL_OK;
}
static int _wrap_ElementNew(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    Element * _result;

    clientData = clientData; argv = argv;
    if ((argc < 1) || (argc > 1)) {
        Tcl_SetResult(interp, "Wrong # args. ElementNew ",TCL_STATIC);
        return TCL_ERROR;
    }
    _result = (Element *)ElementNew();
    SWIG_MakePtr(interp->result, (void *) _result,"_Element_p");
    return TCL_OK;
}
static int _wrap_DocumentNew(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    Document * _result;

    clientData = clientData; argv = argv;
    if ((argc < 1) || (argc > 1)) {
        Tcl_SetResult(interp, "Wrong # args. DocumentNew ",TCL_STATIC);
        return TCL_ERROR;
    }
    _result = (Document *)DocumentNew();
    SWIG_MakePtr(interp->result, (void *) _result,"_Document_p");
    return TCL_OK;
}
static int _wrap_TextNew(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    Text * _result;

    clientData = clientData; argv = argv;
    if ((argc < 1) || (argc > 1)) {
        Tcl_SetResult(interp, "Wrong # args. TextNew ",TCL_STATIC);
        return TCL_ERROR;
    }
    _result = (Text *)TextNew();
    SWIG_MakePtr(interp->result, (void *) _result,"_Text_p");
    return TCL_OK;
}
static int _wrap_InsetNew(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    Inset * _result;

    clientData = clientData; argv = argv;
    if ((argc < 1) || (argc > 1)) {
        Tcl_SetResult(interp, "Wrong # args. InsetNew ",TCL_STATIC);
        return TCL_ERROR;
    }
    _result = (Inset *)InsetNew();
    SWIG_MakePtr(interp->result, (void *) _result,"_Inset_p");
    return TCL_OK;
}
static int _wrap_CDATASectionNew(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    CDATASection * _result;

    clientData = clientData; argv = argv;
    if ((argc < 1) || (argc > 1)) {
        Tcl_SetResult(interp, "Wrong # args. CDATASectionNew ",TCL_STATIC);
        return TCL_ERROR;
    }
    _result = (CDATASection *)CDATASectionNew();
    SWIG_MakePtr(interp->result, (void *) _result,"_CDATASection_p");
    return TCL_OK;
}
static int _wrap_NodeDelete(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    Node * _arg0;

    clientData = clientData; argv = argv;
    if ((argc < 2) || (argc > 2)) {
        Tcl_SetResult(interp, "Wrong # args. NodeDelete { Node * } ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_Node_p")) {
    }
    NodeDelete(_arg0);
    return TCL_OK;
}
static int _wrap_NodeGetNodeType(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    int  _result;
    Node * _arg0;

    clientData = clientData; argv = argv;
    if ((argc < 2) || (argc > 2)) {
        Tcl_SetResult(interp, "Wrong # args. NodeGetNodeType { Node * } ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_Node_p")) {
    }
    _result = (int )NodeGetNodeType(_arg0);
    sprintf(interp->result,"%ld", (long) _result);
    return TCL_OK;
}
static int _wrap_NodeGetParentNode(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    Node * _result;
    Node * _arg0;

    clientData = clientData; argv = argv;
    if ((argc < 2) || (argc > 2)) {
        Tcl_SetResult(interp, "Wrong # args. NodeGetParentNode { Node * } ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_Node_p")) {
    }
    _result = (Node *)NodeGetParentNode(_arg0);
    SWIG_MakePtr(interp->result, (void *) _result,"_Node_p");
    return TCL_OK;
}
static int _wrap_NodeGetOwnerDocument(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    Document * _result;
    Node * _arg0;

    clientData = clientData; argv = argv;
    if ((argc < 2) || (argc > 2)) {
        Tcl_SetResult(interp, "Wrong # args. NodeGetOwnerDocument { Node * } ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_Node_p")) {
    }
    _result = (Document *)NodeGetOwnerDocument(_arg0);
    SWIG_MakePtr(interp->result, (void *) _result,"_Document_p");
    return TCL_OK;
}
static int _wrap_NodeGetPreviousSibling(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    Node * _result;
    Node * _arg0;

    clientData = clientData; argv = argv;
    if ((argc < 2) || (argc > 2)) {
        Tcl_SetResult(interp, "Wrong # args. NodeGetPreviousSibling { Node * } ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_Node_p")) {
    }
    _result = (Node *)NodeGetPreviousSibling(_arg0);
    SWIG_MakePtr(interp->result, (void *) _result,"_Node_p");
    return TCL_OK;
}
static int _wrap_NodeGetNextSibling(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    Node * _result;
    Node * _arg0;

    clientData = clientData; argv = argv;
    if ((argc < 2) || (argc > 2)) {
        Tcl_SetResult(interp, "Wrong # args. NodeGetNextSibling { Node * } ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_Node_p")) {
    }
    _result = (Node *)NodeGetNextSibling(_arg0);
    SWIG_MakePtr(interp->result, (void *) _result,"_Node_p");
    return TCL_OK;
}
static int _wrap_NodeHasChildNodes(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    int  _result;
    Node * _arg0;

    clientData = clientData; argv = argv;
    if ((argc < 2) || (argc > 2)) {
        Tcl_SetResult(interp, "Wrong # args. NodeHasChildNodes { Node * } ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_Node_p")) {
    }
    _result = (int )NodeHasChildNodes(_arg0);
    sprintf(interp->result,"%ld", (long) _result);
    return TCL_OK;
}
static int _wrap_NodeGetFirstChild(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    Node * _result;
    Node * _arg0;

    clientData = clientData; argv = argv;
    if ((argc < 2) || (argc > 2)) {
        Tcl_SetResult(interp, "Wrong # args. NodeGetFirstChild { Node * } ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_Node_p")) {
    }
    _result = (Node *)NodeGetFirstChild(_arg0);
    SWIG_MakePtr(interp->result, (void *) _result,"_Node_p");
    return TCL_OK;
}
static int _wrap_NodeGetLastChild(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    Node * _result;
    Node * _arg0;

    clientData = clientData; argv = argv;
    if ((argc < 2) || (argc > 2)) {
        Tcl_SetResult(interp, "Wrong # args. NodeGetLastChild { Node * } ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_Node_p")) {
    }
    _result = (Node *)NodeGetLastChild(_arg0);
    SWIG_MakePtr(interp->result, (void *) _result,"_Node_p");
    return TCL_OK;
}
static int _wrap_NodeAppendChild(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    Node * _arg0;
    Node * _arg1;

    clientData = clientData; argv = argv;
    if ((argc < 3) || (argc > 3)) {
        Tcl_SetResult(interp, "Wrong # args. NodeAppendChild { Node * } { Node * } ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_Node_p")) {
    }
    if (SWIG_GetPtr(argv[2],(void **) &_arg1,"_Node_p")) {
    }
    NodeAppendChild(_arg0,_arg1);
    return TCL_OK;
}
static int _wrap_NodeInsertBefore(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    Node * _arg0;
    Node * _arg1;
    Node * _arg2;

    clientData = clientData; argv = argv;
    if ((argc < 4) || (argc > 4)) {
        Tcl_SetResult(interp, "Wrong # args. NodeInsertBefore { Node * } { Node * } { Node * } ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_Node_p")) {
    }
    if (SWIG_GetPtr(argv[2],(void **) &_arg1,"_Node_p")) {
    }
    if (SWIG_GetPtr(argv[3],(void **) &_arg2,"_Node_p")) {
    }
    NodeInsertBefore(_arg0,_arg1,_arg2);
    return TCL_OK;
}
static int _wrap_NodeReplaceChild(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    Node * _result;
    Node * _arg0;
    Node * _arg1;
    Node * _arg2;

    clientData = clientData; argv = argv;
    if ((argc < 4) || (argc > 4)) {
        Tcl_SetResult(interp, "Wrong # args. NodeReplaceChild { Node * } { Node * } { Node * } ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_Node_p")) {
    }
    if (SWIG_GetPtr(argv[2],(void **) &_arg1,"_Node_p")) {
    }
    if (SWIG_GetPtr(argv[3],(void **) &_arg2,"_Node_p")) {
    }
    _result = (Node *)NodeReplaceChild(_arg0,_arg1,_arg2);
    SWIG_MakePtr(interp->result, (void *) _result,"_Node_p");
    return TCL_OK;
}
static int _wrap_NodeRemoveChild(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    Node * _result;
    Node * _arg0;
    Node * _arg1;

    clientData = clientData; argv = argv;
    if ((argc < 3) || (argc > 3)) {
        Tcl_SetResult(interp, "Wrong # args. NodeRemoveChild { Node * } { Node * } ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_Node_p")) {
    }
    if (SWIG_GetPtr(argv[2],(void **) &_arg1,"_Node_p")) {
    }
    _result = (Node *)NodeRemoveChild(_arg0,_arg1);
    SWIG_MakePtr(interp->result, (void *) _result,"_Node_p");
    return TCL_OK;
}
static int _wrap_NodePrint(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    Node * _arg0;
    int  _arg1;

    clientData = clientData; argv = argv;
    if ((argc < 3) || (argc > 3)) {
        Tcl_SetResult(interp, "Wrong # args. NodePrint { Node * } { int  } ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_Node_p")) {
    }
    _arg1 = (int ) atol(argv[2]);
    NodePrint(_arg0,_arg1);
    return TCL_OK;
}
static int _wrap_NodeToText(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    char * _result;
    Node * _arg0;

    clientData = clientData; argv = argv;
    if ((argc < 2) || (argc > 2)) {
        Tcl_SetResult(interp, "Wrong # args. NodeToText { Node * } ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_Node_p")) {
    }
    _result = (char *)NodeToText(_arg0);
    Tcl_SetResult(interp, (char *) _result, TCL_VOLATILE);
{
	free (_result);
}
    return TCL_OK;
}
static int _wrap_NodeParentLookup(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    Node * _result;
    Node * _arg0;
    char * _arg1;
    char * _arg2;

    clientData = clientData; argv = argv;
    if ((argc < 4) || (argc > 4)) {
        Tcl_SetResult(interp, "Wrong # args. NodeParentLookup { Node * } { char * } { char * } ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_Node_p")) {
    }
    _arg1 = argv[2];
    _arg2 = argv[3];
    _result = (Node *)NodeParentLookup(_arg0,_arg1,_arg2);
    SWIG_MakePtr(interp->result, (void *) _result,"_Node_p");
    return TCL_OK;
}
static int _wrap_NodeChildLookup(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    Node * _result;
    Node * _arg0;
    char * _arg1;
    char * _arg2;

    clientData = clientData; argv = argv;
    if ((argc < 4) || (argc > 4)) {
        Tcl_SetResult(interp, "Wrong # args. NodeChildLookup { Node * } { char * } { char * } ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_Node_p")) {
    }
    _arg1 = argv[2];
    _arg2 = argv[3];
    _result = (Node *)NodeChildLookup(_arg0,_arg1,_arg2);
    SWIG_MakePtr(interp->result, (void *) _result,"_Node_p");
    return TCL_OK;
}
static int _wrap_NodeGetSuccessor(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    Node * _result;
    Node * _arg0;

    clientData = clientData; argv = argv;
    if ((argc < 2) || (argc > 2)) {
        Tcl_SetResult(interp, "Wrong # args. NodeGetSuccessor { Node * } ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_Node_p")) {
    }
    _result = (Node *)NodeGetSuccessor(_arg0);
    SWIG_MakePtr(interp->result, (void *) _result,"_Node_p");
    return TCL_OK;
}
static int _wrap_TextGetData(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    char * _result;
    Text * _arg0;

    clientData = clientData; argv = argv;
    if ((argc < 2) || (argc > 2)) {
        Tcl_SetResult(interp, "Wrong # args. TextGetData { Text * } ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_Text_p")) {
    }
    _result = (char *)TextGetData(_arg0);
    Tcl_SetResult(interp, (char *) _result, TCL_VOLATILE);
    return TCL_OK;
}
static int _wrap_TextSetData(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    Text * _arg0;
    char * _arg1;

    clientData = clientData; argv = argv;
    if ((argc < 3) || (argc > 3)) {
        Tcl_SetResult(interp, "Wrong # args. TextSetData { Text * } { char * } ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_Text_p")) {
    }
    _arg1 = argv[2];
    TextSetData(_arg0,_arg1);
    return TCL_OK;
}
static int _wrap_CDATASectionGetData(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    char * _result;
    CDATASection * _arg0;

    clientData = clientData; argv = argv;
    if ((argc < 2) || (argc > 2)) {
        Tcl_SetResult(interp, "Wrong # args. CDATASectionGetData { CDATASection * } ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_CDATASection_p")) {
    }
    _result = (char *)CDATASectionGetData(_arg0);
    Tcl_SetResult(interp, (char *) _result, TCL_VOLATILE);
    return TCL_OK;
}
static int _wrap_CDATASectionSetData(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    CDATASection * _arg0;
    char * _arg1;

    clientData = clientData; argv = argv;
    if ((argc < 3) || (argc > 3)) {
        Tcl_SetResult(interp, "Wrong # args. CDATASectionSetData { CDATASection * } { char * } ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_CDATASection_p")) {
    }
    _arg1 = argv[2];
    CDATASectionSetData(_arg0,_arg1);
    return TCL_OK;
}
static int _wrap_DocumentGetElementsByTagName(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    NodeList * _result;
    Document * _arg0;
    char * _arg1;

    clientData = clientData; argv = argv;
    if ((argc < 3) || (argc > 3)) {
        Tcl_SetResult(interp, "Wrong # args. DocumentGetElementsByTagName { Document * } { char * } ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_Document_p")) {
    }
    _arg1 = argv[2];
    _result = (NodeList *)DocumentGetElementsByTagName(_arg0,_arg1);
    SWIG_MakePtr(interp->result, (void *) _result,"_NodeList_p");
    return TCL_OK;
}
static int _wrap_ElementGetTagName(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    char * _result;
    Element * _arg0;

    clientData = clientData; argv = argv;
    if ((argc < 2) || (argc > 2)) {
        Tcl_SetResult(interp, "Wrong # args. ElementGetTagName { Element * } ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_Element_p")) {
    }
    _result = (char *)ElementGetTagName(_arg0);
    Tcl_SetResult(interp, (char *) _result, TCL_VOLATILE);
    return TCL_OK;
}
static int _wrap_ElementSetTagName(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    Element * _arg0;
    char * _arg1;

    clientData = clientData; argv = argv;
    if ((argc < 3) || (argc > 3)) {
        Tcl_SetResult(interp, "Wrong # args. ElementSetTagName { Element * } { char * } ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_Element_p")) {
    }
    _arg1 = argv[2];
    ElementSetTagName(_arg0,_arg1);
    return TCL_OK;
}
static int _wrap_ElementGetNSPrefix(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    char * _result;
    Element * _arg0;

    clientData = clientData; argv = argv;
    if ((argc < 2) || (argc > 2)) {
        Tcl_SetResult(interp, "Wrong # args. ElementGetNSPrefix { Element * } ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_Element_p")) {
    }
    _result = (char *)ElementGetNSPrefix(_arg0);
    Tcl_SetResult(interp, (char *) _result, TCL_VOLATILE);
    return TCL_OK;
}
static int _wrap_ElementSetNSPrefix(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    Element * _arg0;
    char * _arg1;

    clientData = clientData; argv = argv;
    if ((argc < 3) || (argc > 3)) {
        Tcl_SetResult(interp, "Wrong # args. ElementSetNSPrefix { Element * } { char * } ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_Element_p")) {
    }
    _arg1 = argv[2];
    ElementSetNSPrefix(_arg0,_arg1);
    return TCL_OK;
}
static int _wrap_ElementGetAttribute(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    char * _result;
    Element * _arg0;
    char * _arg1;

    clientData = clientData; argv = argv;
    if ((argc < 3) || (argc > 3)) {
        Tcl_SetResult(interp, "Wrong # args. ElementGetAttribute { Element * } { char * } ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_Element_p")) {
    }
    _arg1 = argv[2];
    _result = (char *)ElementGetAttribute(_arg0,_arg1);
    Tcl_SetResult(interp, (char *) _result, TCL_VOLATILE);
    return TCL_OK;
}
static int _wrap_ElementSetAttribute(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    Element * _arg0;
    char * _arg1;
    char * _arg2;

    clientData = clientData; argv = argv;
    if ((argc < 4) || (argc > 4)) {
        Tcl_SetResult(interp, "Wrong # args. ElementSetAttribute { Element * } { char * } { char * } ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_Element_p")) {
    }
    _arg1 = argv[2];
    _arg2 = argv[3];
    ElementSetAttribute(_arg0,_arg1,_arg2);
    return TCL_OK;
}
static int _wrap_ElementSetContents(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    Element * _arg0;
    char * _arg1;

    clientData = clientData; argv = argv;
    if ((argc < 3) || (argc > 3)) {
        Tcl_SetResult(interp, "Wrong # args. ElementSetContents { Element * } { char * } ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_Element_p")) {
    }
    _arg1 = argv[2];
    ElementSetContents(_arg0,_arg1);
    return TCL_OK;
}
static int _wrap_ElementGetContents(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    char * _result;
    Element * _arg0;

    clientData = clientData; argv = argv;
    if ((argc < 2) || (argc > 2)) {
        Tcl_SetResult(interp, "Wrong # args. ElementGetContents { Element * } ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_Element_p")) {
    }
    _result = (char *)ElementGetContents(_arg0);
    Tcl_SetResult(interp, (char *) _result, TCL_VOLATILE);
{
	free (_result);
}
    return TCL_OK;
}
static int _wrap_ElementSetDefaultAttributes(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    Element * _arg0;

    clientData = clientData; argv = argv;
    if ((argc < 2) || (argc > 2)) {
        Tcl_SetResult(interp, "Wrong # args. ElementSetDefaultAttributes { Element * } ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_Element_p")) {
    }
    ElementSetDefaultAttributes(_arg0);
    return TCL_OK;
}
static int _wrap_ElementSetInherited(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    Element * _arg0;

    clientData = clientData; argv = argv;
    if ((argc < 2) || (argc > 2)) {
        Tcl_SetResult(interp, "Wrong # args. ElementSetInherited { Element * } ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_Element_p")) {
    }
    ElementSetInherited(_arg0);
    return TCL_OK;
}
static int _wrap_ElementGetElementsByTagName(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    NodeList * _result;
    Element * _arg0;
    char * _arg1;

    clientData = clientData; argv = argv;
    if ((argc < 3) || (argc > 3)) {
        Tcl_SetResult(interp, "Wrong # args. ElementGetElementsByTagName { Element * } { char * } ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_Element_p")) {
    }
    _arg1 = argv[2];
    _result = (NodeList *)ElementGetElementsByTagName(_arg0,_arg1);
    SWIG_MakePtr(interp->result, (void *) _result,"_NodeList_p");
    return TCL_OK;
}
static int _wrap_NodeListNew(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    NodeList * _result;

    clientData = clientData; argv = argv;
    if ((argc < 1) || (argc > 1)) {
        Tcl_SetResult(interp, "Wrong # args. NodeListNew ",TCL_STATIC);
        return TCL_ERROR;
    }
    _result = (NodeList *)NodeListNew();
    SWIG_MakePtr(interp->result, (void *) _result,"_NodeList_p");
    return TCL_OK;
}
static int _wrap_NodeListDelete(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    NodeList * _arg0;

    clientData = clientData; argv = argv;
    if ((argc < 2) || (argc > 2)) {
        Tcl_SetResult(interp, "Wrong # args. NodeListDelete { NodeList * } ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_NodeList_p")) {
    }
    NodeListDelete(_arg0);
    return TCL_OK;
}
static int _wrap_NodeListAppendItem(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    int  _result;
    NodeList * _arg0;
    Node * _arg1;

    clientData = clientData; argv = argv;
    if ((argc < 3) || (argc > 3)) {
        Tcl_SetResult(interp, "Wrong # args. NodeListAppendItem { NodeList * } { Node * } ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_NodeList_p")) {
    }
    if (SWIG_GetPtr(argv[2],(void **) &_arg1,"_Node_p")) {
    }
    _result = (int )NodeListAppendItem(_arg0,_arg1);
    sprintf(interp->result,"%ld", (long) _result);
    return TCL_OK;
}
static int _wrap_NodeListGetLength(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    int  _result;
    NodeList * _arg0;

    clientData = clientData; argv = argv;
    if ((argc < 2) || (argc > 2)) {
        Tcl_SetResult(interp, "Wrong # args. NodeListGetLength { NodeList * } ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_NodeList_p")) {
    }
    _result = (int )NodeListGetLength(_arg0);
    sprintf(interp->result,"%ld", (long) _result);
    return TCL_OK;
}
static int _wrap_NodeListGetItem(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    Node * _result;
    NodeList * _arg0;
    int  _arg1;

    clientData = clientData; argv = argv;
    if ((argc < 3) || (argc > 3)) {
        Tcl_SetResult(interp, "Wrong # args. NodeListGetItem { NodeList * } { int  } ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_NodeList_p")) {
    }
    _arg1 = (int ) atol(argv[2]);
    _result = (Node *)NodeListGetItem(_arg0,_arg1);
    SWIG_MakePtr(interp->result, (void *) _result,"_Node_p");
    return TCL_OK;
}
static int _wrap_NodeListRemoveItem(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    Node * _result;
    NodeList * _arg0;
    Node * _arg1;

    clientData = clientData; argv = argv;
    if ((argc < 3) || (argc > 3)) {
        Tcl_SetResult(interp, "Wrong # args. NodeListRemoveItem { NodeList * } { Node * } ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_NodeList_p")) {
    }
    if (SWIG_GetPtr(argv[2],(void **) &_arg1,"_Node_p")) {
    }
    _result = (Node *)NodeListRemoveItem(_arg0,_arg1);
    SWIG_MakePtr(interp->result, (void *) _result,"_Node_p");
    return TCL_OK;
}
static int _wrap_ElementMatch(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    NodeList * _result;
    Element * _arg0;
    Element * _arg1;

    clientData = clientData; argv = argv;
    if ((argc < 3) || (argc > 3)) {
        Tcl_SetResult(interp, "Wrong # args. ElementMatch { Element * } { Element * } ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_Element_p")) {
    }
    if (SWIG_GetPtr(argv[2],(void **) &_arg1,"_Element_p")) {
    }
    _result = (NodeList *)ElementMatch(_arg0,_arg1);
    SWIG_MakePtr(interp->result, (void *) _result,"_NodeList_p");
    return TCL_OK;
}
static int _wrap_ParserNew(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    Parser * _result;

    clientData = clientData; argv = argv;
    if ((argc < 1) || (argc > 1)) {
        Tcl_SetResult(interp, "Wrong # args. ParserNew ",TCL_STATIC);
        return TCL_ERROR;
    }
    _result = (Parser *)ParserNew();
    SWIG_MakePtr(interp->result, (void *) _result,"_Parser_p");
    return TCL_OK;
}
static int _wrap_ParserDelete(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    Parser * _arg0;

    clientData = clientData; argv = argv;
    if ((argc < 2) || (argc > 2)) {
        Tcl_SetResult(interp, "Wrong # args. ParserDelete { Parser * } ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_Parser_p")) {
    }
    ParserDelete(_arg0);
    return TCL_OK;
}
static int _wrap_ParserSetStartElement(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    Parser * _arg0;
    Element * _arg1;

    clientData = clientData; argv = argv;
    if ((argc < 3) || (argc > 3)) {
        Tcl_SetResult(interp, "Wrong # args. ParserSetStartElement { Parser * } { Element * } ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_Parser_p")) {
    }
    if (SWIG_GetPtr(argv[2],(void **) &_arg1,"_Element_p")) {
    }
    ParserSetStartElement(_arg0,_arg1);
    return TCL_OK;
}
static int _wrap_ParserSetDocument(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    Parser * _arg0;
    Document * _arg1;

    clientData = clientData; argv = argv;
    if ((argc < 3) || (argc > 3)) {
        Tcl_SetResult(interp, "Wrong # args. ParserSetDocument { Parser * } { Document * } ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_Parser_p")) {
    }
    if (SWIG_GetPtr(argv[2],(void **) &_arg1,"_Document_p")) {
    }
    ParserSetDocument(_arg0,_arg1);
    return TCL_OK;
}
static int _wrap_ParserSetURI(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    Parser * _arg0;
    char * _arg1;

    clientData = clientData; argv = argv;
    if ((argc < 3) || (argc > 3)) {
        Tcl_SetResult(interp, "Wrong # args. ParserSetURI { Parser * } { char * } ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_Parser_p")) {
    }
    _arg1 = argv[2];
    ParserSetURI(_arg0,_arg1);
    return TCL_OK;
}
static int _wrap_ParserProcessData(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    Element * _result;
    Parser * _arg0;
    char * _arg1;
    char * _arg2;

    clientData = clientData; argv = argv;
    if ((argc < 4) || (argc > 4)) {
        Tcl_SetResult(interp, "Wrong # args. ParserProcessData { Parser * } { char * } { char * } ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_Parser_p")) {
    }
    _arg1 = argv[2];
    _arg2 = argv[3];
    _result = (Element *)ParserProcessData(_arg0,_arg1,_arg2);
    SWIG_MakePtr(interp->result, (void *) _result,"_Element_p");
    return TCL_OK;
}
SWIGEXPORT(int,Kinoparser_Init)(Tcl_Interp *interp) {
	 if (interp == 0) 
		 return TCL_ERROR;
	 Tcl_CreateCommand(interp, SWIG_prefix "NodeNew", _wrap_NodeNew, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "ElementNew", _wrap_ElementNew, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "DocumentNew", _wrap_DocumentNew, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "TextNew", _wrap_TextNew, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "InsetNew", _wrap_InsetNew, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "CDATASectionNew", _wrap_CDATASectionNew, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "NodeDelete", _wrap_NodeDelete, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "NodeGetNodeType", _wrap_NodeGetNodeType, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "NodeGetParentNode", _wrap_NodeGetParentNode, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "NodeGetOwnerDocument", _wrap_NodeGetOwnerDocument, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "NodeGetPreviousSibling", _wrap_NodeGetPreviousSibling, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "NodeGetNextSibling", _wrap_NodeGetNextSibling, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "NodeHasChildNodes", _wrap_NodeHasChildNodes, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "NodeGetFirstChild", _wrap_NodeGetFirstChild, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "NodeGetLastChild", _wrap_NodeGetLastChild, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "NodeAppendChild", _wrap_NodeAppendChild, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "NodeInsertBefore", _wrap_NodeInsertBefore, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "NodeReplaceChild", _wrap_NodeReplaceChild, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "NodeRemoveChild", _wrap_NodeRemoveChild, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "NodePrint", _wrap_NodePrint, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "NodeToText", _wrap_NodeToText, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "NodeParentLookup", _wrap_NodeParentLookup, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "NodeChildLookup", _wrap_NodeChildLookup, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "NodeGetSuccessor", _wrap_NodeGetSuccessor, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "TextGetData", _wrap_TextGetData, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "TextSetData", _wrap_TextSetData, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "CDATASectionGetData", _wrap_CDATASectionGetData, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "CDATASectionSetData", _wrap_CDATASectionSetData, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "DocumentGetElementsByTagName", _wrap_DocumentGetElementsByTagName, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "ElementGetTagName", _wrap_ElementGetTagName, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "ElementSetTagName", _wrap_ElementSetTagName, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "ElementGetNSPrefix", _wrap_ElementGetNSPrefix, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "ElementSetNSPrefix", _wrap_ElementSetNSPrefix, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "ElementGetAttribute", _wrap_ElementGetAttribute, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "ElementSetAttribute", _wrap_ElementSetAttribute, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "ElementSetContents", _wrap_ElementSetContents, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "ElementGetContents", _wrap_ElementGetContents, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "ElementSetDefaultAttributes", _wrap_ElementSetDefaultAttributes, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "ElementSetInherited", _wrap_ElementSetInherited, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "ElementGetElementsByTagName", _wrap_ElementGetElementsByTagName, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "NodeListNew", _wrap_NodeListNew, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "NodeListDelete", _wrap_NodeListDelete, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "NodeListAppendItem", _wrap_NodeListAppendItem, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "NodeListGetLength", _wrap_NodeListGetLength, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "NodeListGetItem", _wrap_NodeListGetItem, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "NodeListRemoveItem", _wrap_NodeListRemoveItem, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "ElementMatch", _wrap_ElementMatch, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "ParserNew", _wrap_ParserNew, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "ParserDelete", _wrap_ParserDelete, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "ParserSetStartElement", _wrap_ParserSetStartElement, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "ParserSetDocument", _wrap_ParserSetDocument, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "ParserSetURI", _wrap_ParserSetURI, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "ParserProcessData", _wrap_ParserProcessData, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
/*
 * These are the pointer type-equivalency mappings. 
 * (Used by the SWIG pointer type-checker).
 */
	 SWIG_RegisterMapping("_signed_long","_long",0);
	 SWIG_RegisterMapping("_long","_unsigned_long",0);
	 SWIG_RegisterMapping("_long","_signed_long",0);
	 SWIG_RegisterMapping("_unsigned_long","_long",0);
	 SWIG_RegisterMapping("_signed_int","_int",0);
	 SWIG_RegisterMapping("_unsigned_short","_short",0);
	 SWIG_RegisterMapping("_signed_short","_short",0);
	 SWIG_RegisterMapping("_unsigned_int","_int",0);
	 SWIG_RegisterMapping("_short","_unsigned_short",0);
	 SWIG_RegisterMapping("_short","_signed_short",0);
	 SWIG_RegisterMapping("_int","_unsigned_int",0);
	 SWIG_RegisterMapping("_int","_signed_int",0);
	 return TCL_OK;
}
