/*
 * FILE : WidgetTclWrap.c
 * 
 * This file was automatically generated by :
 * Simplified Wrapper and Interface Generator (SWIG)
 * Version 1.1 (Patch 5)
 * 
 * Portions Copyright (c) 1995-1998
 * The University of Utah and The Regents of the University of California.
 * Permission is granted to distribute this file in any manner provided
 * this notice remains intact.
 * 
 * Do not make changes to this file--changes will be lost!
 *
 */


#define SWIGCODE
/* Implementation : TCL 7.x */

#define INCLUDE_TCL    <tcl.h>
#define INCLUDE_TK     <tk.h>
#include INCLUDE_TCL
#include <string.h>
#include <stdlib.h>
#define SWIGTCL
/*
 * $Header: /b2/dmb/SWIG/SWIG1.0b3/swig_lib/tcl/RCS/swigtcl.cfg,v 1.1 1996/05/22 19:47:45 beazley Exp $
 * 
 * swigtcl.cfg
 *
 * This file is modified from a platform independent file provided
 * by Sun.   With any luck this will allow SWIG generated wrapper
 * files to work on Unix, Windows, and Macintosh.
 *
 * Revision History
 * $Log: swigtcl.cfg,v $
 * Revision 1.1  1996/05/22 19:47:45  beazley
 * Initial revision
 *
 *
 * -- Dave Beazley, May 2, 1996.
 *
 *	This file is an example of a Tcl dynamically loadable extension.
 *
 * Copyright (c) 1996 by Sun Microsystems, Inc.
 *
 * See the file "license.terms" for information on usage and redistribution
 * of this file, and for a DISCLAIMER OF ALL WARRANTIES.
 *
 */

#if defined(__WIN32__)
#   define WIN32_LEAN_AND_MEAN
#   include <windows.h>
#   undef WIN32_LEAN_AND_MEAN

/*
 * VC++ has an alternate entry point called DllMain, so we need to rename
 * our entry point.
 */

#   if defined(_MSC_VER)
#	define SWIGEXPORT(a,b) __declspec(dllexport) a b
#	define DllEntryPoint DllMain
#   else
#	if defined(__BORLANDC__)
#	    define SWIGEXPORT(a,b) a _export b
#	else
#	    define SWIGEXPORT(a,b) a b
#	endif
#   endif
#else
#   define SWIGEXPORT(a,b) a b
#endif

/*
 *----------------------------------------------------------------------
 *
 * DllEntryPoint --
 *
 *	This wrapper function is used by Windows to invoke the
 *	initialization code for the DLL.  If we are compiling
 *	with Visual C++, this routine will be renamed to DllMain.
 *	routine.
 *
 * Results:
 *	Returns TRUE;
 *
 * Side effects:
 *	None.
 *
 *----------------------------------------------------------------------
 */

#ifdef __WIN32__
BOOL APIENTRY
DllEntryPoint(HINSTANCE hInst, DWORD reason, LPVOID reserved)
{
    return TRUE;
}
#endif

#ifdef __cplusplus
extern "C" {
#endif
extern void SWIG_MakePtr(char *, void *, char *);
extern void SWIG_RegisterMapping(char *, char *, void *(*)(void *));
extern char *SWIG_GetPtr(char *, void **, char *);
#ifdef __cplusplus
}
#endif
#define SWIG_init    Kinowidget_Init
#define SWIG_name    "kinowidget"
#define SWIG_prefix  ""
#define SWIG_namespace ""

#ifdef __cplusplus
extern "C" {
#endif
#ifdef MAC_TCL
#pragma export on
#endif
SWIGEXPORT(int,Kinowidget_Init)(Tcl_Interp *);
#ifdef MAC_TCL
#pragma export off
#endif
#ifdef __cplusplus
}
#endif

#ifdef NATIVE_NETWORKING
#include <errno.h>
#include <signal.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <sys/fcntl.h>
#include <sys/wait.h>
#include <netinet/in.h>
#include <netdb.h>
#include <regex.h>

#ifdef HAVE_LIBPTHREAD
#include <pthread.h>
#endif

#include <Net.h>
#endif

#include <KinoParser.h>
#include <AHDRuntime.h>
#include <HTMLFormTags.h>

static int _wrap_HTMLInputElementNew(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    Element * _result;
    Document * _arg0;

    clientData = clientData; argv = argv;
    if ((argc < 2) || (argc > 2)) {
        Tcl_SetResult(interp, "Wrong # args. HTMLInputElementNew { Document * } ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_Document_p")) {
    }
    _result = (Element *)HTMLInputElementNew(_arg0);
    SWIG_MakePtr(interp->result, (void *) _result,"_Element_p");
    return TCL_OK;
}
static int _wrap_HTMLTextareaElementNew(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    Element * _result;
    Document * _arg0;

    clientData = clientData; argv = argv;
    if ((argc < 2) || (argc > 2)) {
        Tcl_SetResult(interp, "Wrong # args. HTMLTextareaElementNew { Document * } ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_Document_p")) {
    }
    _result = (Element *)HTMLTextareaElementNew(_arg0);
    SWIG_MakePtr(interp->result, (void *) _result,"_Element_p");
    return TCL_OK;
}
static int _wrap_HTMLButtonElementNew(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    Element * _result;
    Document * _arg0;

    clientData = clientData; argv = argv;
    if ((argc < 2) || (argc > 2)) {
        Tcl_SetResult(interp, "Wrong # args. HTMLButtonElementNew { Document * } ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_Document_p")) {
    }
    _result = (Element *)HTMLButtonElementNew(_arg0);
    SWIG_MakePtr(interp->result, (void *) _result,"_Element_p");
    return TCL_OK;
}
static int _wrap_ElementSetCSSProperties(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    Element * _arg0;

    clientData = clientData; argv = argv;
    if ((argc < 2) || (argc > 2)) {
        Tcl_SetResult(interp, "Wrong # args. ElementSetCSSProperties { Element * } ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_Element_p")) {
    }
    ElementSetCSSProperties(_arg0);
    return TCL_OK;
}
static int _wrap_ElementSetCSSProperty(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    Element * _arg0;
    char * _arg1;
    char * _arg2;

    clientData = clientData; argv = argv;
    if ((argc < 4) || (argc > 4)) {
        Tcl_SetResult(interp, "Wrong # args. ElementSetCSSProperty { Element * } { char * } { char * } ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_Element_p")) {
    }
    _arg1 = argv[2];
    _arg2 = argv[3];
    ElementSetCSSProperty(_arg0,_arg1,_arg2);
    return TCL_OK;
}
static int _wrap_ElementGetCSSProperty(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    char * _result;
    char * _arg0;

    clientData = clientData; argv = argv;
    if ((argc < 2) || (argc > 2)) {
        Tcl_SetResult(interp, "Wrong # args. ElementGetCSSProperty { char * } ",TCL_STATIC);
        return TCL_ERROR;
    }
    _arg0 = argv[1];
    _result = (char *)ElementGetCSSProperty(_arg0);
    Tcl_SetResult(interp, (char *) _result, TCL_VOLATILE);
    return TCL_OK;
}
SWIGEXPORT(int,Kinowidget_Init)(Tcl_Interp *interp) {
	 if (interp == 0) 
		 return TCL_ERROR;
	 Tcl_CreateCommand(interp, SWIG_prefix "HTMLInputElementNew", _wrap_HTMLInputElementNew, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "HTMLTextareaElementNew", _wrap_HTMLTextareaElementNew, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "HTMLButtonElementNew", _wrap_HTMLButtonElementNew, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "ElementSetCSSProperties", _wrap_ElementSetCSSProperties, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "ElementSetCSSProperty", _wrap_ElementSetCSSProperty, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, SWIG_prefix "ElementGetCSSProperty", _wrap_ElementGetCSSProperty, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
/*
 * These are the pointer type-equivalency mappings. 
 * (Used by the SWIG pointer type-checker).
 */
	 SWIG_RegisterMapping("_signed_long","_long",0);
	 SWIG_RegisterMapping("_long","_unsigned_long",0);
	 SWIG_RegisterMapping("_long","_signed_long",0);
	 SWIG_RegisterMapping("_unsigned_long","_long",0);
	 SWIG_RegisterMapping("_signed_int","_int",0);
	 SWIG_RegisterMapping("_unsigned_short","_short",0);
	 SWIG_RegisterMapping("_signed_short","_short",0);
	 SWIG_RegisterMapping("_unsigned_int","_int",0);
	 SWIG_RegisterMapping("_short","_unsigned_short",0);
	 SWIG_RegisterMapping("_short","_signed_short",0);
	 SWIG_RegisterMapping("_int","_unsigned_int",0);
	 SWIG_RegisterMapping("_int","_signed_int",0);
	 return TCL_OK;
}
