/*
 * FILE : WidgetLuaWrap.c
 * 
 * This file was automatically generated by :
 * Simplified Wrapper and Interface Generator (SWIG)
 * Version 1.1 (Patch 5)
 * 
 * Portions Copyright (c) 1995-1998
 * The University of Utah and The Regents of the University of California.
 * Permission is granted to distribute this file in any manner provided
 * this notice remains intact.
 * 
 * Do not make changes to this file--changes will be lost!
 *
 */


#define SWIGCODE
/* Implementation : Lua */

#include <lua.h>

#ifdef __cplusplus
extern "C" {
#endif
extern void SWIG_MakePtr(char *, void *, char *);
extern void SWIG_RegisterMapping(char *, char *, void *(*)(void *));
extern char *SWIG_GetPtr(char *, void **, char *);
#ifdef __cplusplus
}
#endif

#ifdef NATIVE_NETWORKING
#include <errno.h>
#include <signal.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <sys/fcntl.h>
#include <sys/wait.h>
#include <netinet/in.h>
#include <netdb.h>
#include <regex.h>

#ifdef HAVE_LIBPTHREAD
#include <pthread.h>
#endif

#include <Net.h>
#endif

#include <KinoParser.h>
#include <AHDRuntime.h>
#include <HTMLFormTags.h>

static void _wrap_HTMLInputElementNew(void) {

    Element * _result;
    Document * _arg0;

{
  if (!lua_isnil (lua_getparam (1))) _arg0 = lua_getuserdata (lua_getparam (1));
  else _arg0 = NULL;
}
    _result = (Element *)HTMLInputElementNew(_arg0);
{
  if (_result != NULL) lua_pushuserdata (_result);
  else lua_pushnil ();
}
    
}
static void _wrap_HTMLTextareaElementNew(void) {

    Element * _result;
    Document * _arg0;

{
  if (!lua_isnil (lua_getparam (1))) _arg0 = lua_getuserdata (lua_getparam (1));
  else _arg0 = NULL;
}
    _result = (Element *)HTMLTextareaElementNew(_arg0);
{
  if (_result != NULL) lua_pushuserdata (_result);
  else lua_pushnil ();
}
    
}
static void _wrap_HTMLButtonElementNew(void) {

    Element * _result;
    Document * _arg0;

{
  if (!lua_isnil (lua_getparam (1))) _arg0 = lua_getuserdata (lua_getparam (1));
  else _arg0 = NULL;
}
    _result = (Element *)HTMLButtonElementNew(_arg0);
{
  if (_result != NULL) lua_pushuserdata (_result);
  else lua_pushnil ();
}
    
}
static void _wrap_ElementSetCSSProperties(void) {

    Element * _arg0;

{
  if (!lua_isnil (lua_getparam (1))) _arg0 = lua_getuserdata (lua_getparam (1));
  else _arg0 = NULL;
}
    ElementSetCSSProperties(_arg0);
    
}
static void _wrap_ElementSetCSSProperty(void) {

    Element * _arg0;
    char * _arg1;
    char * _arg2;

{
  if (!lua_isnil (lua_getparam (1))) _arg0 = lua_getuserdata (lua_getparam (1));
  else _arg0 = NULL;
}
{
  _arg1 = lua_getstring (lua_getparam (2));
}
{
  _arg2 = lua_getstring (lua_getparam (3));
}
    ElementSetCSSProperty(_arg0,_arg1,_arg2);
    
}
static void _wrap_ElementGetCSSProperty(void) {

    char * _result;
    char * _arg0;

{
  _arg0 = lua_getstring (lua_getparam (1));
}
    _result = (char *)ElementGetCSSProperty(_arg0);
{
  lua_pushstring (_result);
}
    
}
void kinowidgetlua_init (void) {
	 lua_register ("HTMLInputElementNew",_wrap_HTMLInputElementNew);
	 lua_register ("HTMLTextareaElementNew",_wrap_HTMLTextareaElementNew);
	 lua_register ("HTMLButtonElementNew",_wrap_HTMLButtonElementNew);
	 lua_register ("ElementSetCSSProperties",_wrap_ElementSetCSSProperties);
	 lua_register ("ElementSetCSSProperty",_wrap_ElementSetCSSProperty);
	 lua_register ("ElementGetCSSProperty",_wrap_ElementGetCSSProperty);
/*
 * These are the pointer type-equivalency mappings. 
 * (Used by the SWIG pointer type-checker).
 */
	 SWIG_RegisterMapping("_signed_long","_long",0);
	 SWIG_RegisterMapping("_long","_unsigned_long",0);
	 SWIG_RegisterMapping("_long","_signed_long",0);
	 SWIG_RegisterMapping("_unsigned_long","_long",0);
	 SWIG_RegisterMapping("_signed_int","_int",0);
	 SWIG_RegisterMapping("_unsigned_short","_short",0);
	 SWIG_RegisterMapping("_signed_short","_short",0);
	 SWIG_RegisterMapping("_unsigned_int","_int",0);
	 SWIG_RegisterMapping("_short","_unsigned_short",0);
	 SWIG_RegisterMapping("_short","_signed_short",0);
	 SWIG_RegisterMapping("_int","_unsigned_int",0);
	 SWIG_RegisterMapping("_int","_signed_int",0);
}
